version: "3.1"

services:
  hackerblocks.projectx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
      - 7020:7020
      - 7357:7357
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 1m30s
      timeout: 10s
      retries: 3
