name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ development ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: yarn install
    - name: Build
      run: yarn build --env staging
    - name: Create temp Directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: mkdir -p ~/frontends/hackerblocks.staging/temp
    - name: Upload Build
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "dist"
        target: "~/frontends/hackerblocks.staging/temp"
    - name: Replace New Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: rm -rf ~/frontends/hackerblocks.staging/* && cp -rf ~/frontends/hackerblocks.staging/temp/dist/* ~/frontends/hackerblocks.staging && rm -rf ~/frontends/hackerblocks.staging/temp